// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: rtpproxy/rtpproxy.proto

package rtpproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SdpOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Sdp           string                 `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SdpOffer) Reset() {
	*x = SdpOffer{}
	mi := &file_rtpproxy_rtpproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SdpOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdpOffer) ProtoMessage() {}

func (x *SdpOffer) ProtoReflect() protoreflect.Message {
	mi := &file_rtpproxy_rtpproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdpOffer.ProtoReflect.Descriptor instead.
func (*SdpOffer) Descriptor() ([]byte, []int) {
	return file_rtpproxy_rtpproxy_proto_rawDescGZIP(), []int{0}
}

func (x *SdpOffer) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SdpOffer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type SdpAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SdpAnswer) Reset() {
	*x = SdpAnswer{}
	mi := &file_rtpproxy_rtpproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SdpAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdpAnswer) ProtoMessage() {}

func (x *SdpAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_rtpproxy_rtpproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdpAnswer.ProtoReflect.Descriptor instead.
func (*SdpAnswer) Descriptor() ([]byte, []int) {
	return file_rtpproxy_rtpproxy_proto_rawDescGZIP(), []int{1}
}

func (x *SdpAnswer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

var File_rtpproxy_rtpproxy_proto protoreflect.FileDescriptor

var file_rtpproxy_rtpproxy_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x72, 0x74, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x72, 0x74, 0x70, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x74, 0x70, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x22, 0x35, 0x0a, 0x08, 0x53, 0x64, 0x70, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x64, 0x70, 0x22, 0x1d, 0x0a, 0x09, 0x53, 0x64,
	0x70, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x64, 0x70, 0x32, 0x49, 0x0a, 0x0f, 0x52, 0x74, 0x70,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0b,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x64, 0x70, 0x12, 0x12, 0x2e, 0x72, 0x74,
	0x70, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x64, 0x70, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x1a,
	0x13, 0x2e, 0x72, 0x74, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x64, 0x70, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x72, 0x74, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_rtpproxy_rtpproxy_proto_rawDescOnce sync.Once
	file_rtpproxy_rtpproxy_proto_rawDescData []byte
)

func file_rtpproxy_rtpproxy_proto_rawDescGZIP() []byte {
	file_rtpproxy_rtpproxy_proto_rawDescOnce.Do(func() {
		file_rtpproxy_rtpproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rtpproxy_rtpproxy_proto_rawDesc), len(file_rtpproxy_rtpproxy_proto_rawDesc)))
	})
	return file_rtpproxy_rtpproxy_proto_rawDescData
}

var file_rtpproxy_rtpproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rtpproxy_rtpproxy_proto_goTypes = []any{
	(*SdpOffer)(nil),  // 0: rtpproxy.SdpOffer
	(*SdpAnswer)(nil), // 1: rtpproxy.SdpAnswer
}
var file_rtpproxy_rtpproxy_proto_depIdxs = []int32{
	0, // 0: rtpproxy.RtpProxyService.ExchangeSdp:input_type -> rtpproxy.SdpOffer
	1, // 1: rtpproxy.RtpProxyService.ExchangeSdp:output_type -> rtpproxy.SdpAnswer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rtpproxy_rtpproxy_proto_init() }
func file_rtpproxy_rtpproxy_proto_init() {
	if File_rtpproxy_rtpproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rtpproxy_rtpproxy_proto_rawDesc), len(file_rtpproxy_rtpproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rtpproxy_rtpproxy_proto_goTypes,
		DependencyIndexes: file_rtpproxy_rtpproxy_proto_depIdxs,
		MessageInfos:      file_rtpproxy_rtpproxy_proto_msgTypes,
	}.Build()
	File_rtpproxy_rtpproxy_proto = out.File
	file_rtpproxy_rtpproxy_proto_goTypes = nil
	file_rtpproxy_rtpproxy_proto_depIdxs = nil
}
