// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: rtpproxy/rtpproxy.proto

package rtpproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RtpProxyService_ExchangeSdp_FullMethodName = "/rtpproxy.RtpProxyService/ExchangeSdp"
)

// RtpProxyServiceClient is the client API for RtpProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// protoc --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --proto_path=proto --go_out=protogen --go-grpc_out=protogen proto/rtpproxy/rtpproxy.proto
type RtpProxyServiceClient interface {
	ExchangeSdp(ctx context.Context, in *SdpOffer, opts ...grpc.CallOption) (*SdpAnswer, error)
}

type rtpProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRtpProxyServiceClient(cc grpc.ClientConnInterface) RtpProxyServiceClient {
	return &rtpProxyServiceClient{cc}
}

func (c *rtpProxyServiceClient) ExchangeSdp(ctx context.Context, in *SdpOffer, opts ...grpc.CallOption) (*SdpAnswer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SdpAnswer)
	err := c.cc.Invoke(ctx, RtpProxyService_ExchangeSdp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RtpProxyServiceServer is the server API for RtpProxyService service.
// All implementations must embed UnimplementedRtpProxyServiceServer
// for forward compatibility.
//
// protoc --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --proto_path=proto --go_out=protogen --go-grpc_out=protogen proto/rtpproxy/rtpproxy.proto
type RtpProxyServiceServer interface {
	ExchangeSdp(context.Context, *SdpOffer) (*SdpAnswer, error)
	mustEmbedUnimplementedRtpProxyServiceServer()
}

// UnimplementedRtpProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRtpProxyServiceServer struct{}

func (UnimplementedRtpProxyServiceServer) ExchangeSdp(context.Context, *SdpOffer) (*SdpAnswer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeSdp not implemented")
}
func (UnimplementedRtpProxyServiceServer) mustEmbedUnimplementedRtpProxyServiceServer() {}
func (UnimplementedRtpProxyServiceServer) testEmbeddedByValue()                         {}

// UnsafeRtpProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RtpProxyServiceServer will
// result in compilation errors.
type UnsafeRtpProxyServiceServer interface {
	mustEmbedUnimplementedRtpProxyServiceServer()
}

func RegisterRtpProxyServiceServer(s grpc.ServiceRegistrar, srv RtpProxyServiceServer) {
	// If the following call pancis, it indicates UnimplementedRtpProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RtpProxyService_ServiceDesc, srv)
}

func _RtpProxyService_ExchangeSdp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdpOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtpProxyServiceServer).ExchangeSdp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtpProxyService_ExchangeSdp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtpProxyServiceServer).ExchangeSdp(ctx, req.(*SdpOffer))
	}
	return interceptor(ctx, in, info, handler)
}

// RtpProxyService_ServiceDesc is the grpc.ServiceDesc for RtpProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RtpProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rtpproxy.RtpProxyService",
	HandlerType: (*RtpProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeSdp",
			Handler:    _RtpProxyService_ExchangeSdp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rtpproxy/rtpproxy.proto",
}
